apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worklane
resources:
  - namespace.yaml
  - config.yaml
  - mysql/initdb-configmap.yaml
  - mysql/svc.yaml
  - mysql/statefulset.yaml
  - redpanda/svc.yaml
  - redpanda/statefulset.yaml
  - redis/svc.yaml
  - redis/deployment.yaml
  - otp-api/svc.yaml
  - otp-api/deployment.yaml
  - auth-svc/svc.yaml
  - auth-svc/deployment.yaml
  - otp-dispatcher/deployment.yaml
  - ingress/middlewares.yaml
  - observability/alloy-config.yaml
  - observability/alloy.yaml
